name: Setup
description: Perform standard setup and install dependencies using pnpm.
inputs:
  node-version:
    description: The version of Node.js to install
    required: true
    default: 24.5.0

runs:
  using: composite
  steps:
    - name: Install bun
      uses: oven-sh/setup-bun@v2
    - name: Install dependencies
      shell: bash
      run: bun install
